import 'package:hive/hive.dart';

part 'badge_model.g.dart'; // Generated by build_runner

@HiveType(typeId: 1) // Unique typeId (0 used for Progress)
class QuizBadge extends HiveObject {
  @HiveField(0)
  final String name;

  @HiveField(1)
  final String category;

  @HiveField(2)
  final bool earned;

  QuizBadge({
    required this.name,
    required this.category,
    required this.earned,
  });
}