import 'package:hive/hive.dart';
import 'question_model.dart';

part 'category_model.g.dart'; // Generated by build_runner

@HiveType(typeId: 2) // Unique typeId (0 for Progress, 1 for QuizBadge)
class QuizCategory {
  @HiveField(0)
  final String name;

  @HiveField(1)
  final List<Question> questions;

  QuizCategory({
    required this.name,
    required this.questions,
  });

  factory QuizCategory.fromJson(Map<String, dynamic> json) {
    return QuizCategory(
      name: json['name'] as String,
      questions: (json['questions'] as List)
          .map((q) => Question.fromJson(q as Map<String, dynamic>))
          .toList(),
    );
  }
}